//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer.
        /// </summary>
        public static string archer {
            get {
                return ResourceManager.GetString("archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na wojnie często wygrywa ten, kto sprawnie potrafi zarządzać łucznikami. Klasa ta cechuje się ogromnym zasięgiem strzału, ale jest krucha i warto trzymać są na dystans..
        /// </summary>
        public static string archer_desc {
            get {
                return ResourceManager.GetString("archer_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łucznik wykonuje strzał z łuku zadający obrażenia równe {0} + [ilość oczek na kości].
        /// </summary>
        public static string archer_primary_desc {
            get {
                return ResourceManager.GetString("archer_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strzał z łuku.
        /// </summary>
        public static string archer_primary_name {
            get {
                return ResourceManager.GetString("archer_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łucznik wykorzystuje magiczną esencję by pokierować strzałę w słaby punkt przeciwnika i zadaje obrażenia równe {0} +[ilość oczek na kości].
        /// </summary>
        public static string archer_skill_desc {
            get {
                return ResourceManager.GetString("archer_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precyzyjne trafienie.
        /// </summary>
        public static string archer_skill_name {
            get {
                return ResourceManager.GetString("archer_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assasin.
        /// </summary>
        public static string assassin {
            get {
                return ResourceManager.GetString("assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwinny zabójca wyczekujący na swoje ofiary, by w dogodnej chwili móc zakończyć ich żywot. Ostry jak brzytwa sztylet oraz specjalny uniform pozwala mu być niezwykle szybkim i precyzyjnym w zadawaniu śmierci. Jednak nie warto wystawiać go na walkę z całą armią jednocześnie, bardziej podoba mu się wyłapywanie celów jeden po drugim..
        /// </summary>
        public static string assassin_desc {
            get {
                return ResourceManager.GetString("assassin_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabójca wykonuje cięcie sztyletem i zadaje {0} + [ilość oczek na kości] obrażeń..
        /// </summary>
        public static string assassin_primary_desc {
            get {
                return ResourceManager.GetString("assassin_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cięcie sztyletem.
        /// </summary>
        public static string assassin_primary_name {
            get {
                return ResourceManager.GetString("assassin_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asasyn wykonuje uderzenie wykorzystując swoją kondycję oraz magiczną esencję i zadaje {0} + {1} + [ilość oczek na kości].
        /// </summary>
        public static string assassin_skill_desc {
            get {
                return ResourceManager.GetString("assassin_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uderzenie z impetem.
        /// </summary>
        public static string assassin_skill_name {
            get {
                return ResourceManager.GetString("assassin_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string attack {
            get {
                return ResourceManager.GetString("attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axeman.
        /// </summary>
        public static string axeman {
            get {
                return ResourceManager.GetString("axeman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wojownicy dzielą się na rodzaje ze względu na oręż, którym walczą. Topornicy należą do bezwzględnych wojowników, ich siła oraz wytrzymałość jest niesamowicie potężna w walce, dlatego warto trzymać ich przy życiu..
        /// </summary>
        public static string axeman_desc {
            get {
                return ResourceManager.GetString("axeman_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topornik używa swojego oręża, by zadać obrażenia równe {0} + [ilość oczek na kości]..
        /// </summary>
        public static string axeman_primary_desc {
            get {
                return ResourceManager.GetString("axeman_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uderzenie toporem.
        /// </summary>
        public static string axeman_primary_name {
            get {
                return ResourceManager.GetString("axeman_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topornik wykorzystuje magiczną esencję by utworzyć kopię topora, który następnie rzuca zadając obrażenia równe {0} + [ilość oczek na kości].
        /// </summary>
        public static string axeman_skill_desc {
            get {
                return ResourceManager.GetString("axeman_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryształowy rzut.
        /// </summary>
        public static string axeman_skill_name {
            get {
                return ResourceManager.GetString("axeman_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only skip movement after selecting pawn.
        /// </summary>
        public static string cannot_skip_movemnt {
            get {
                return ResourceManager.GetString("cannot_skip_movemnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string condition {
            get {
                return ResourceManager.GetString("condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string defender {
            get {
                return ResourceManager.GetString("defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Członek Królewskiej gwardii, doskonale wyszkolony żołnierz. Jego głównym zadaniem na polu bitwy jest ochrona sojuszników, ale również walka za swojego Króla. Jako oddany koronie z miłości do kraju złoży swoje życie w walce..
        /// </summary>
        public static string defender_desc {
            get {
                return ResourceManager.GetString("defender_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrońca wykonuje cios mieczem i zadaje obrażenia równe {0} + [ilość oczek na kości].
        /// </summary>
        public static string defender_primary_desc {
            get {
                return ResourceManager.GetString("defender_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uderzenie mieczem.
        /// </summary>
        public static string defender_primary_name {
            get {
                return ResourceManager.GetString("defender_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrońca korzysta z magicznej esencji by wykonać zamaszyste cięcie które rani wroga obrażeniami o sile {0} + [ilość oczek na kości].
        /// </summary>
        public static string defender_skill_desc {
            get {
                return ResourceManager.GetString("defender_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamaszysty cios.
        /// </summary>
        public static string defender_skill_name {
            get {
                return ResourceManager.GetString("defender_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string defense {
            get {
                return ResourceManager.GetString("defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Round.
        /// </summary>
        public static string end_round {
            get {
                return ResourceManager.GetString("end_round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enebul.
        /// </summary>
        public static string enebul {
            get {
                return ResourceManager.GetString("enebul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feith&apos;s.
        /// </summary>
        public static string feith {
            get {
                return ResourceManager.GetString("feith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutejsi mędrcy i bardowie opowiadają historie o złowieszczej i zadziornej bogini wojny imieniem Faith. Dzierżyła ona w dłoniach dwa miecze i na wszelkich wojnach jej duch wstępował w najsilniejszych wojowników, czyniąc ich niepokonanymi, a przynajmniej tak słyszałem … ENG.
        /// </summary>
        public static string floor_attack_desc {
            get {
                return ResourceManager.GetString("floor_attack_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda podlogi attack.
        /// </summary>
        public static string floor_attack_legend {
            get {
                return ResourceManager.GetString("floor_attack_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are&apos;n any bonuses on this field.
        /// </summary>
        public static string floor_base_bonuses {
            get {
                return ResourceManager.GetString("floor_base_bonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamienne płyty pokrywające wąwóz prowadzący do Enebul. Dziś będą patrzeć na przelewającą się krew i na szerzącą się śmierć. Będą wchłaniały magiczną esencję i zapamiętają zwycięskie chorągwie..
        /// </summary>
        public static string floor_base_desc {
            get {
                return ResourceManager.GetString("floor_base_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEgenda podlogi normal.
        /// </summary>
        public static string floor_base_legeng {
            get {
                return ResourceManager.GetString("floor_base_legeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamienna płyta z wąwozu ENG.
        /// </summary>
        public static string floor_base_title {
            get {
                return ResourceManager.GetString("floor_base_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blessing.
        /// </summary>
        public static string floor_blessing {
            get {
                return ResourceManager.GetString("floor_blessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field bonuses: +{0} to {1}.
        /// </summary>
        public static string floor_bonus {
            get {
                return ResourceManager.GetString("floor_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prastare księgi posiadały na swoich kartach opis pewnego rodzaju bóstwa zwanego Rhea. Była ona obrończynią uciśnionych i słabych. Jej symbolem była tarcza, a uciekających się do niej obdarzała błogosławieństwem, które chroniło od śmierci....
        /// </summary>
        public static string floor_def_desc {
            get {
                return ResourceManager.GetString("floor_def_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda podlogi def.
        /// </summary>
        public static string floor_def_legend {
            get {
                return ResourceManager.GetString("floor_def_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na polu widnieją buty. Według mistycznych zwojów płyta była pobłogosławiona przez patrona podróżnych i kupców - Saula. Jego względy miały zapewnić sprawność, prędkość oraz nadludzką zwinność ... ENG.
        /// </summary>
        public static string floor_move_desc {
            get {
                return ResourceManager.GetString("floor_move_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda podlogi condition.
        /// </summary>
        public static string floor_move_legend {
            get {
                return ResourceManager.GetString("floor_move_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda Kartazyny, tak, tej kartazyny....
        /// </summary>
        public static string kartazine_legend {
            get {
                return ResourceManager.GetString("kartazine_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        public static string king {
            get {
                return ResourceManager.GetString("king", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Król jest najważniejszą osobą w królestwie. On wydaje rozkazy i prowadzi swoje wojska ku zwycięstwu. Złota zbroja jest jego chlubą, a wysadzające ją kryształy budzą grozę w przeciwniku..
        /// </summary>
        public static string king_desc {
            get {
                return ResourceManager.GetString("king_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Król bierze zamach mieczem i zadaje obrażenie równe {0} + [ilość oczek na kości].
        /// </summary>
        public static string king_primary_desc {
            get {
                return ResourceManager.GetString("king_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uderzenie mieczem.
        /// </summary>
        public static string king_primary_name {
            get {
                return ResourceManager.GetString("king_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Król wykorzystuje magiczną esencję swojego miecza by móc zadać ogromne obrażenia {0} + [ ilość oczek na kości]..
        /// </summary>
        public static string king_skill_desc {
            get {
                return ResourceManager.GetString("king_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magia kryształów.
        /// </summary>
        public static string king_skill_name {
            get {
                return ResourceManager.GetString("king_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag.
        /// </summary>
        public static string mag {
            get {
                return ResourceManager.GetString("mag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uczony w królewskich bibliotekach mędrzec, posiadający wiedzę z wszelakich arkan magii. Potrafi rozpętać piekło na ziemi, a swoją moc opiera na ilości esencji magicznej jaka go otacza. Na pierwszy rzut oka starzec powoli poruszający się o lasce, a drzemie w nim niesłychany potencjał..
        /// </summary>
        public static string mag_desc {
            get {
                return ResourceManager.GetString("mag_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag korzysta ze swojego kunsztu by uderzyć wroga wzmocnionym przez zaklęcie kostura zadając {0} + {1}/3 + [ilość oczek na kostce].
        /// </summary>
        public static string mag_primary_desc {
            get {
                return ResourceManager.GetString("mag_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaklęcie bólu.
        /// </summary>
        public static string mag_primary_name {
            get {
                return ResourceManager.GetString("mag_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag korzysta z magicznego zwoju i naznacza płytę. W następnej turze na płytę spłynie potężna energia zadająca w centrum {0} + [ilość oczek na kostce] obrażeń oraz w pobliżu {1} + [ilość oczek na kostce / 2]..
        /// </summary>
        public static string mag_skill_desc {
            get {
                return ResourceManager.GetString("mag_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkan zniszczenia.
        /// </summary>
        public static string mag_skill_name {
            get {
                return ResourceManager.GetString("mag_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marbang.
        /// </summary>
        public static string marbang {
            get {
                return ResourceManager.GetString("marbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaczność kartazyny.
        /// </summary>
        public static string op_kartazine {
            get {
                return ResourceManager.GetString("op_kartazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn.
        /// </summary>
        public static string pawn {
            get {
                return ResourceManager.GetString("pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string pawn_title {
            get {
                return ResourceManager.GetString("pawn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Attack.
        /// </summary>
        public static string primary_attack {
            get {
                return ResourceManager.GetString("primary_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowy atak: {0}
        ///[Zasięg: {1}] [Koszt  {2}].
        /// </summary>
        public static string primary_attack_info {
            get {
                return ResourceManager.GetString("primary_attack_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhea&apos;s.
        /// </summary>
        public static string rhea {
            get {
                return ResourceManager.GetString("rhea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saul&apos;s.
        /// </summary>
        public static string saula {
            get {
                return ResourceManager.GetString("saula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Attack.
        /// </summary>
        public static string skill_attack {
            get {
                return ResourceManager.GetString("skill_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowa umiejętność : {0} 
        ///[Zasięg : {1}] [Koszt : {2}].
        /// </summary>
        public static string skilll_attack_info {
            get {
                return ResourceManager.GetString("skilll_attack_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Movement.
        /// </summary>
        public static string skip_movement {
            get {
                return ResourceManager.GetString("skip_movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Attack Demage: {0}
        ///Skill attack demage: {1}
        ///Primary Attack Range: {2}
        ///Skill attack range: {3}
        ///Condition: {4}
        ///Armor: {5}.
        /// </summary>
        public static string stats_info {
            get {
                return ResourceManager.GetString("stats_info", resourceCulture);
            }
        }
    }
}
