//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer.
        /// </summary>
        public static string archer {
            get {
                return ResourceManager.GetString("archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream archer_attack_0 {
            get {
                return ResourceManager.GetStream("archer_attack_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In war, the one who can manage archers often wins. This class is characterized by a huge range of the shot, but it is fragile and it is worth keeping a distance..
        /// </summary>
        public static string archer_desc {
            get {
                return ResourceManager.GetString("archer_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archer performs a bow shot for {0} + damage [dice count].
        /// </summary>
        public static string archer_primary_desc {
            get {
                return ResourceManager.GetString("archer_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shot from the bow.
        /// </summary>
        public static string archer_primary_name {
            get {
                return ResourceManager.GetString("archer_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archer uses a magic essence to direct the arrow to the opponent&apos;s weak point and deals {0} + damage [dice count].
        /// </summary>
        public static string archer_skill_desc {
            get {
                return ResourceManager.GetString("archer_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise hit.
        /// </summary>
        public static string archer_skill_name {
            get {
                return ResourceManager.GetString("archer_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream assasin_attack_0 {
            get {
                return ResourceManager.GetStream("assasin_attack_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin.
        /// </summary>
        public static string assassin {
            get {
                return ResourceManager.GetString("assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An agile killer waiting for his victims to be able to end their lives at a convenient time. The razor-sharp dagger and the special uniform allow him to be extremely fast and precise in inflicting death. However, it is not worth exposing him to the fight with the whole army at the same time, he likes to catch the targets one by one..
        /// </summary>
        public static string assassin_desc {
            get {
                return ResourceManager.GetString("assassin_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assassin makes a dagger cut and deals {0} + [dice count] for damage..
        /// </summary>
        public static string assassin_primary_desc {
            get {
                return ResourceManager.GetString("assassin_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger cut.
        /// </summary>
        public static string assassin_primary_name {
            get {
                return ResourceManager.GetString("assassin_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin strikes using his condition and magical essence and deals {0} + {1} + [dice count].
        /// </summary>
        public static string assassin_skill_desc {
            get {
                return ResourceManager.GetString("assassin_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact hit.
        /// </summary>
        public static string assassin_skill_name {
            get {
                return ResourceManager.GetString("assassin_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string attack {
            get {
                return ResourceManager.GetString("attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Res/Images/MenuStrings/authors_eng.png.
        /// </summary>
        public static string authors_menu_path {
            get {
                return ResourceManager.GetString("authors_menu_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Res/Images/MenuStrings/authors_eng.png.
        /// </summary>
        public static string authors_path {
            get {
                return ResourceManager.GetString("authors_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axeman.
        /// </summary>
        public static string axeman {
            get {
                return ResourceManager.GetString("axeman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream axeman_attack_0 {
            get {
                return ResourceManager.GetStream("axeman_attack_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warriors are divided into types by the weapons they fight. The axes belong to the ruthless warriors, their strength and endurance is incredibly powerful in combat, so keep them alive..
        /// </summary>
        public static string axeman_desc {
            get {
                return ResourceManager.GetString("axeman_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hatchet uses his weapon to deal {0} + damage [dice count]..
        /// </summary>
        public static string axeman_primary_desc {
            get {
                return ResourceManager.GetString("axeman_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ax hit.
        /// </summary>
        public static string axeman_primary_name {
            get {
                return ResourceManager.GetString("axeman_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ax man uses the magic essence to create a copy of the ax, which he then casts for damage equal to {0} + [dice count].
        /// </summary>
        public static string axeman_skill_desc {
            get {
                return ResourceManager.GetString("axeman_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Throw.
        /// </summary>
        public static string axeman_skill_name {
            get {
                return ResourceManager.GetString("axeman_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only skip movement after selecting pawn.
        /// </summary>
        public static string cannot_skip_movemnt {
            get {
                return ResourceManager.GetString("cannot_skip_movemnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string condition {
            get {
                return ResourceManager.GetString("condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string defender {
            get {
                return ResourceManager.GetString("defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream defender_attack_0 {
            get {
                return ResourceManager.GetStream("defender_attack_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member of the Royal Guard, a well-trained soldier. His main task on the battlefield is to protect his allies, but also to fight for his King. As a devoted crown for love of the country will lay his life in battle..
        /// </summary>
        public static string defender_desc {
            get {
                return ResourceManager.GetString("defender_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The defender strikes with a sword and deals {0} + damage [dice count].
        /// </summary>
        public static string defender_primary_desc {
            get {
                return ResourceManager.GetString("defender_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword strike.
        /// </summary>
        public static string defender_primary_name {
            get {
                return ResourceManager.GetString("defender_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The defender uses a magic essence to make a sweeping cut that hurts the enemy with damage of {0} + [dice count].
        /// </summary>
        public static string defender_skill_desc {
            get {
                return ResourceManager.GetString("defender_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sweeping blow.
        /// </summary>
        public static string defender_skill_name {
            get {
                return ResourceManager.GetString("defender_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string defense {
            get {
                return ResourceManager.GetString("defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dices {
            get {
                return ResourceManager.GetStream("dices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End battle .
        /// </summary>
        public static string end_battle {
            get {
                return ResourceManager.GetString("end_battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish battle.
        /// </summary>
        public static string end_game_bottom_title {
            get {
                return ResourceManager.GetString("end_game_bottom_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And as she stood dazed, he said: I gave you the gift of a Deity. You are immortal now. After that, the eldest rubbed her youngest sister&apos;s neck and saw that she had no wound. However, the old man continued: You who brought me bandages, you will be the goddess of life and you will protect them. Turning to the next one, he said: You who gave me blood and lied to me will be burdened with a curse and you will be a goddess of death and war. At the end he turned his gaze to the youngest and said: You, because of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string end_game_legend {
            get {
                return ResourceManager.GetString("end_game_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] end_game_music {
            get {
                object obj = ResourceManager.GetObject("end_game_music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Game!.
        /// </summary>
        public static string end_game_title {
            get {
                return ResourceManager.GetString("end_game_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Round.
        /// </summary>
        public static string end_round {
            get {
                return ResourceManager.GetString("end_round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enebul.
        /// </summary>
        public static string enebul {
            get {
                return ResourceManager.GetString("enebul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Res/Images/MenuStrings/exit_eng.png.
        /// </summary>
        public static string exit_menu_path {
            get {
                return ResourceManager.GetString("exit_menu_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Res/Images/MenuStrings/exit_eng.png.
        /// </summary>
        public static string exit_path {
            get {
                return ResourceManager.GetString("exit_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feith&apos;s.
        /// </summary>
        public static string feith {
            get {
                return ResourceManager.GetString("feith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sages and bards here tell stories of the sinister and feisty goddess of war named Faith. She wielded two swords in her hands and in all wars her spirit entered the strongest warriors, making them invincible, or so I heard ....
        /// </summary>
        public static string floor_attack_desc {
            get {
                return ResourceManager.GetString("floor_attack_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The daughters took care of the rest of the herd, and in the evening they returned to their home. days passed until the time of fullness came. The three sisters left the house in the evening without saying anything to anyone and went to meet the wanderer. When they arrived, they found a sage. After exchanging greetings, he said: For your faith and deed, I want to give you a special gift. One that no one has yet received. He handed them blue stones, and when he directed them to the moonlight at his request, h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string floor_attack_legend {
            get {
                return ResourceManager.GetString("floor_attack_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are&apos;n any bonuses on this field.
        /// </summary>
        public static string floor_base_bonuses {
            get {
                return ResourceManager.GetString("floor_base_bonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone slabs covering the gorge leading to Enebul. Today they will look at bloodshed and death. They will absorb the magic essence and remember the winning banners..
        /// </summary>
        public static string floor_base_desc {
            get {
                return ResourceManager.GetString("floor_base_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A long, long time ago a family lived in a village, parents and three daughters who took care of farming and sheep farming. One afternoon, when the daughters led the flock to the pasture, passing through a forest nearby, they encountered a stranger who was wounded and lying by the road. When they heard his voice asking for help, the eldest of the sisters ran to help the wounded, and her younger sisters followed her. How can we help you ? Asked concerned, eldest daughter. I am a wanderer, I walked this forest [rest of string was truncated]&quot;;.
        /// </summary>
        public static string floor_base_legeng {
            get {
                return ResourceManager.GetString("floor_base_legeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone plate from a ravine.
        /// </summary>
        public static string floor_base_title {
            get {
                return ResourceManager.GetString("floor_base_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blessing.
        /// </summary>
        public static string floor_blessing {
            get {
                return ResourceManager.GetString("floor_blessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field bonuses: +{0} to {1}.
        /// </summary>
        public static string floor_bonus {
            get {
                return ResourceManager.GetString("floor_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ancient books had on their pages a description of a kind of deity called Rhea. She was the protector of the oppressed and the weak. Her symbol was a shield, and she gave those who fled to her a blessing that protected her from death ....
        /// </summary>
        public static string floor_def_desc {
            get {
                return ResourceManager.GetString("floor_def_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He said to the youngest of daughters: Going into this forest, inside the dense purple bushes you will meet, a stone will lie. A white-brown goo will come out of the stone, take it and without looking behind, run here as soon as possible. And to his third daughter he said: There is a bowl and two swords in my purse, they have razor-sharp blades, take them and roll blood from the ram because I feel very thirsty and the water has run out, be careful not to let your blood fall on you hands. The sisters agreed a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string floor_def_legend {
            get {
                return ResourceManager.GetString("floor_def_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are shoes on the field. According to mystical scrolls, the album was blessed by the patron of travelers and merchants - Saul. His considerations were to ensure efficiency, speed and superhuman agility ....
        /// </summary>
        public static string floor_move_desc {
            get {
                return ResourceManager.GetString("floor_move_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meanwhile, the youngest, walking in the dense forest, noticed the dense purple bushes, as the stranger described them, and when she entered them, she saw a stone from the story and mucus escaping from it. Remembering the words of the sage, she took the substance in her hands and quickly ran to where she came from. The third of the sisters, when she was waiting for her siblings, as requested, the wanderer reached for her swords and, having killed the ram while drawing blood into the bowl, and accidentally di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string floor_move_legend {
            get {
                return ResourceManager.GetString("floor_move_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barginda&apos;s Gorge.
        /// </summary>
        public static string gorge_barginda {
            get {
                return ResourceManager.GetString("gorge_barginda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        public static string king {
            get {
                return ResourceManager.GetString("king", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream king_attack_0 {
            get {
                return ResourceManager.GetStream("king_attack_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The king is the most important person in the kingdom. He gives orders and leads his army to victory. Golden armor is his pride, and the crystals that blow it up are terrifying for the opponent..
        /// </summary>
        public static string king_desc {
            get {
                return ResourceManager.GetString("king_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The King swings the sword and deals {0} + damage [dice count].
        /// </summary>
        public static string king_primary_desc {
            get {
                return ResourceManager.GetString("king_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword strike.
        /// </summary>
        public static string king_primary_name {
            get {
                return ResourceManager.GetString("king_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The king uses the magical essence of his sword to deal huge damage {0} + [dice count].
        /// </summary>
        public static string king_skill_desc {
            get {
                return ResourceManager.GetString("king_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic of crystals.
        /// </summary>
        public static string king_skill_name {
            get {
                return ResourceManager.GetString("king_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag.
        /// </summary>
        public static string mag {
            get {
                return ResourceManager.GetString("mag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream mag_attack_0 {
            get {
                return ResourceManager.GetStream("mag_attack_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sage scholar in the royal libraries, knowledgeable in all kinds of magic. He can unleash hell on earth, and his power is based on the amount of magical essence that surrounds him. At first glance, the old man is slowly moving about with a cane, and he has incredible potential..
        /// </summary>
        public static string mag_desc {
            get {
                return ResourceManager.GetString("mag_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mage uses his craftsmanship to heal an ally. The treatment is equal [dice count].
        /// </summary>
        public static string mag_primary_desc {
            get {
                return ResourceManager.GetString("mag_primary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pain spell.
        /// </summary>
        public static string mag_primary_name {
            get {
                return ResourceManager.GetString("mag_primary_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream mag_skill_blue_0 {
            get {
                return ResourceManager.GetStream("mag_skill_blue_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The magician uses the magic scroll and marks the disc. In the next turn, powerful energy will flow to the disc, inflicting damage in the center {0} + [dice count] and near {1} + [dice count  / 2]..
        /// </summary>
        public static string mag_skill_desc {
            get {
                return ResourceManager.GetString("mag_skill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope of destruction.
        /// </summary>
        public static string mag_skill_name {
            get {
                return ResourceManager.GetString("mag_skill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream mag_skill_red_0 {
            get {
                return ResourceManager.GetStream("mag_skill_red_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///In {0} rounds, an attack with a strength of {1} dmg will be made here.
        /// </summary>
        public static string magskill_desc {
            get {
                return ResourceManager.GetString("magskill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marbang.
        /// </summary>
        public static string marbang {
            get {
                return ResourceManager.GetString("marbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string maximize {
            get {
                return ResourceManager.GetString("maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Res/Images/Others/menu_back_eng.png.
        /// </summary>
        public static string menu_back {
            get {
                return ResourceManager.GetString("menu_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minizize.
        /// </summary>
        public static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] music_back {
            get {
                object obj = ResourceManager.GetObject("music_back", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Sounds.
        /// </summary>
        public static string mute_dialogs {
            get {
                return ResourceManager.GetString("mute_dialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Music.
        /// </summary>
        public static string mute_music {
            get {
                return ResourceManager.GetString("mute_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string new_game {
            get {
                return ResourceManager.GetString("new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Res/Images/MenuStrings/newgame_eng.png.
        /// </summary>
        public static string newgame_menu_path {
            get {
                return ResourceManager.GetString("newgame_menu_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catarzine&apos;s providence.
        /// </summary>
        public static string op_kartazine {
            get {
                return ResourceManager.GetString("op_kartazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Options.
        /// </summary>
        public static string options_hide {
            get {
                return ResourceManager.GetString("options_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn.
        /// </summary>
        public static string pawn {
            get {
                return ResourceManager.GetString("pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string pawn_title {
            get {
                return ResourceManager.GetString("pawn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Attack.
        /// </summary>
        public static string primary_attack {
            get {
                return ResourceManager.GetString("primary_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Attack:
        ///{0}
        ///[Coverage: {1}] [Cost {2}].
        /// </summary>
        public static string primary_attack_info {
            get {
                return ResourceManager.GetString("primary_attack_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure about quitting game?.
        /// </summary>
        public static string quit_game_confirmation {
            get {
                return ResourceManager.GetString("quit_game_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit game.
        /// </summary>
        public static string quit_game_title {
            get {
                return ResourceManager.GetString("quit_game_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhea&apos;s.
        /// </summary>
        public static string rhea {
            get {
                return ResourceManager.GetString("rhea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saul&apos;s.
        /// </summary>
        public static string saula {
            get {
                return ResourceManager.GetString("saula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Attack.
        /// </summary>
        public static string skill_attack {
            get {
                return ResourceManager.GetString("skill_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional skill:
        ///{0}
        ///[Coverage: {1}] [Cost: {2}].
        /// </summary>
        public static string skilll_attack_info {
            get {
                return ResourceManager.GetString("skilll_attack_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Movement.
        /// </summary>
        public static string skip_movement {
            get {
                return ResourceManager.GetString("skip_movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May the power of Catarzine be with you!.
        /// </summary>
        public static string start_game_bottom_title {
            get {
                return ResourceManager.GetString("start_game_bottom_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barginda Gorge, this is where the battle will take place today. Enebul, the kingdom behind the ravine at the Gulf of Enebul, flourishing with trade in blue crystals and gold, is today fighting the kingdom of Marbang, a hard-ruled empire, once an ally, now a hellish enemy. Blood, tainted by the magic of crystals that will now pour over the marble slabs blasting the ravine, will give them history and magical essence. The question, whose banners will remember ....?.
        /// </summary>
        public static string starting_legend {
            get {
                return ResourceManager.GetString("starting_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Enebul.
        /// </summary>
        public static string starting_title {
            get {
                return ResourceManager.GetString("starting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Damage: {0} {6}
        ///Skill damage: {1} {6}
        ///Primary Range: {2}
        ///Skill range: {3}
        ///Condition: {4} {7}
        ///Armor: {5} {8}.
        /// </summary>
        public static string stats_info {
            get {
                return ResourceManager.GetString("stats_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on the battlefield.
        /// </summary>
        public static string stay_battle {
            get {
                return ResourceManager.GetString("stay_battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute Sounds.
        /// </summary>
        public static string unmute_dialogs {
            get {
                return ResourceManager.GetString("unmute_dialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute Music.
        /// </summary>
        public static string unmute_music {
            get {
                return ResourceManager.GetString("unmute_music", resourceCulture);
            }
        }
    }
}
